# Generated by Django 2.0.3 on 2018-03-29 14:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20180310_1022'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='following',
            unique_together={('follower', 'followed')},
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('rater', 'post')},
        ),
    ]
